//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoCmsTest.Models
{
	/// <summary>BanKorteActie</summary>
	[PublishedContentModel("banKorteActie")]
	public partial class BanKorteActie : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "banKorteActie";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BanKorteActie(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BanKorteActie, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// KaOmschrijving
		///</summary>
		[ImplementPropertyType("kaOmschrijving")]
		public string KaOmschrijving
		{
			get { return this.GetPropertyValue<string>("kaOmschrijving"); }
		}

		///<summary>
		/// KaTitel
		///</summary>
		[ImplementPropertyType("kaTitel")]
		public string KaTitel
		{
			get { return this.GetPropertyValue<string>("kaTitel"); }
		}
	}
}
