//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoCmsTest.Models
{
	/// <summary>DocumentTypeNoTemplate</summary>
	[PublishedContentModel("documentTypeNoTemplate")]
	public partial class DocumentTypeNoTemplate : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "documentTypeNoTemplate";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DocumentTypeNoTemplate(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DocumentTypeNoTemplate, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// DocumentTypeNoTemplate_MarkDown: Een markdown tekstveld
		///</summary>
		[ImplementPropertyType("documentTypeNoTemplate_MarkDown")]
		public IHtmlString DocumentTypeNoTemplate_MarkDown
		{
			get { return this.GetPropertyValue<IHtmlString>("documentTypeNoTemplate_MarkDown"); }
		}

		///<summary>
		/// DocumentTypeNoTemplate_TitleText: Title of this item
		///</summary>
		[ImplementPropertyType("documentTypeNoTemplate_TitleText")]
		public string DocumentTypeNoTemplate_TitleText
		{
			get { return this.GetPropertyValue<string>("documentTypeNoTemplate_TitleText"); }
		}
	}
}
